import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/structure/Footer";
import Navbar from "../components/structure/navbar";
import { Provider } from "../components/ui/provider";
import AuthContextProvider from "../context/useAuthContext";
import StreamVideoContext from "../context/StreamVideo";
import { getSession } from "./actions/auth";
import { VerifySession } from "./lib/verifySession";
import StreamWrapper from "../components/structure/StreamWrapper";
import { Suspense } from "react";
import { Spinner, Text, VStack } from "@chakra-ui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body suppressHydrationWarning suppressContentEditableWarning>    
         
        <Provider>
          
          <AuthContextProvider
          ><Suspense fallback={<VStack background={'#1d1d1d'} justifyContent={'center'} alignItems={'center'} height={'100%'} width={'100%'}>
            <Spinner size={'md'}/>
          </VStack>}>
       
              <StreamWrapper>
            
                <Navbar/>
                {children}
                <Footer/>
              </StreamWrapper>
          </Suspense>
            
           
           </AuthContextProvider>
        </Provider>
       </body>
    </html>
  );
}
