import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/structure/Footer";
import Navbar from "../components/structure/navbar";
import { Provider } from "../components/ui/provider";
import AuthContextProvider from "../context/useAuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body suppressHydrationWarning suppressContentEditableWarning>
        <Provider>
          <AuthContextProvider>

          
          <Navbar/>
           {children}
           <Footer/>
           </AuthContextProvider>
        </Provider>
       </body>
    </html>
  );
}
